// Short correct/incorrect chimes played once per submitted answer (SPEC.md §4/§6),
// matching Duolingo's per-round ding/buzz. Distinct from src/audio/player.ts's
// AudioClipPlayer — these are bundled local assets (generated by
// scripts/audio/generate-feedback-sounds.ts), not per-word Serbian clips fetched
// from Convex/R2, so they get their own tiny player pair instead of going through
// the text-keyed clip cache.

import { createAudioPlayer, type AudioPlayer } from "expo-audio";

/**
 * Lazily creates (once) and replays the correct/incorrect chime players. A
 * class (mirroring AudioClipPlayer) rather than bare module state so it's
 * instantiable fresh per test instead of leaking a singleton across specs.
 */
export class FeedbackSoundPlayer {
  private correctPlayer: AudioPlayer | null = null;
  private incorrectPlayer: AudioPlayer | null = null;

  // eslint-disable-next-line @typescript-eslint/no-require-imports
  private createCorrectPlayer = (): AudioPlayer => createAudioPlayer(require("../../assets/audio/correct.wav"));
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  private createIncorrectPlayer = (): AudioPlayer => createAudioPlayer(require("../../assets/audio/incorrect.wav"));

  private replay(player: AudioPlayer): void {
    player.pause();
    void player.seekTo(0);
    player.play();
  }

  /**
   * Plays `player`, recreating it once via `create` and retrying if the native
   * side has gone stale (e.g. "Server was dead when activation request was
   * made" — happens across a JS reload or the app being backgrounded long
   * enough for iOS to tear down the audio session). Without this, a single
   * stale reference would silently break the chime for the rest of the session.
   */
  private replayWithRetry(current: AudioPlayer, create: () => AudioPlayer, save: (p: AudioPlayer) => void): void {
    try {
      this.replay(current);
    } catch {
      const fresh = create();
      save(fresh);
      this.replay(fresh);
    }
  }

  playCorrect(): void {
    if (!this.correctPlayer) this.correctPlayer = this.createCorrectPlayer();
    this.replayWithRetry(
      this.correctPlayer,
      this.createCorrectPlayer,
      (p) => {
        this.correctPlayer = p;
      },
    );
  }

  playIncorrect(): void {
    if (!this.incorrectPlayer) this.incorrectPlayer = this.createIncorrectPlayer();
    this.replayWithRetry(
      this.incorrectPlayer,
      this.createIncorrectPlayer,
      (p) => {
        this.incorrectPlayer = p;
      },
    );
  }
}

/** App-wide singleton — one shared player pair, per src/audio/player.ts's pattern. */
export const feedbackSoundPlayer = new FeedbackSoundPlayer();

export function playCorrectSound(): void {
  feedbackSoundPlayer.playCorrect();
}

export function playIncorrectSound(): void {
  feedbackSoundPlayer.playIncorrect();
}
