// Short correct/incorrect chimes played once per submitted answer (SPEC.md §4/§6),
// matching Duolingo's per-round ding/buzz. Distinct from src/audio/player.ts's
// AudioClipPlayer — these are bundled local assets (generated by
// scripts/audio/generate-feedback-sounds.ts), not per-word Serbian clips fetched
// from Convex/R2, so they get their own tiny player pair instead of going through
// the text-keyed clip cache.
//
// Same crash-proofing contract as player.ts (see its header): iOS can invalidate
// the native session/player at any time on a real device; a play call must NEVER
// throw to its caller (this module's playCorrect was the site of the first
// on-device crash). On failure: revive the audio session, recreate the player,
// retry once (async); if that fails too, skip the chime silently.

import { createAudioPlayer, type AudioPlayer } from "expo-audio";
import { reviveAudioSession } from "./audioSession";

type ChimeKind = "correct" | "incorrect";

/**
 * Lazily creates (once) and replays the correct/incorrect chime players. A
 * class (mirroring AudioClipPlayer) rather than bare module state so it's
 * instantiable fresh per test instead of leaking a singleton across specs.
 */
export class FeedbackSoundPlayer {
  private players: Partial<Record<ChimeKind, AudioPlayer>> = {};

  private create(kind: ChimeKind): AudioPlayer {
    return kind === "correct"
      ? // eslint-disable-next-line @typescript-eslint/no-require-imports
        createAudioPlayer(require("../../assets/audio/correct.wav"))
      : // eslint-disable-next-line @typescript-eslint/no-require-imports
        createAudioPlayer(require("../../assets/audio/incorrect.wav"));
  }

  private replay(player: AudioPlayer): void {
    player.pause();
    void player.seekTo(0);
    player.play();
  }

  /** Plays the chime; never throws (see header). */
  private playChime(kind: ChimeKind): void {
    try {
      const player = (this.players[kind] ??= this.create(kind));
      this.replay(player);
    } catch {
      void this.recover(kind);
    }
  }

  private async recover(kind: ChimeKind): Promise<void> {
    try {
      await reviveAudioSession();
      const fresh = this.create(kind);
      this.players[kind] = fresh;
      this.replay(fresh);
    } catch {
      // Skip this chime; the next answer walks the same revive path again.
    }
  }

  playCorrect(): void {
    this.playChime("correct");
  }

  playIncorrect(): void {
    this.playChime("incorrect");
  }
}

/** App-wide singleton — one shared player pair, per src/audio/player.ts's pattern. */
export const feedbackSoundPlayer = new FeedbackSoundPlayer();

export function playCorrectSound(): void {
  feedbackSoundPlayer.playCorrect();
}

export function playIncorrectSound(): void {
  feedbackSoundPlayer.playIncorrect();
}
