// Short correct/incorrect chimes played once per submitted answer (SPEC.md §4/§6),
// matching Duolingo's per-round ding/buzz. Distinct from src/audio/player.ts's
// AudioClipPlayer — these are bundled local assets (generated by
// scripts/audio/generate-feedback-sounds.ts), not per-word Serbian clips fetched
// from Convex/R2, so they get their own tiny player pair instead of going through
// the text-keyed clip cache.

import { createAudioPlayer, type AudioPlayer } from "expo-audio";

/**
 * Lazily creates (once) and replays the correct/incorrect chime players. A
 * class (mirroring AudioClipPlayer) rather than bare module state so it's
 * instantiable fresh per test instead of leaking a singleton across specs.
 */
export class FeedbackSoundPlayer {
  private correctPlayer: AudioPlayer | null = null;
  private incorrectPlayer: AudioPlayer | null = null;

  private getCorrectPlayer(): AudioPlayer {
    if (!this.correctPlayer) {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      this.correctPlayer = createAudioPlayer(require("../../assets/audio/correct.wav"));
    }
    return this.correctPlayer;
  }

  private getIncorrectPlayer(): AudioPlayer {
    if (!this.incorrectPlayer) {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      this.incorrectPlayer = createAudioPlayer(require("../../assets/audio/incorrect.wav"));
    }
    return this.incorrectPlayer;
  }

  private replay(player: AudioPlayer): void {
    player.pause();
    void player.seekTo(0);
    player.play();
  }

  playCorrect(): void {
    this.replay(this.getCorrectPlayer());
  }

  playIncorrect(): void {
    this.replay(this.getIncorrectPlayer());
  }
}

/** App-wide singleton — one shared player pair, per src/audio/player.ts's pattern. */
export const feedbackSoundPlayer = new FeedbackSoundPlayer();

export function playCorrectSound(): void {
  feedbackSoundPlayer.playCorrect();
}

export function playIncorrectSound(): void {
  feedbackSoundPlayer.playIncorrect();
}
